import Head from "next/head";
import Image from "next/image";
import Navigation from "../components/Navigation";
import Header from "../components/Header";
import Stack from "../components/Stack";
import Work from "../components/Work";
import Contact from "../components/Contact";

export async function getStaticProps() {
  let _initialState = true;
  return {
    props: {
      _initialState,
    },
  };
}

export default function Home({ _initialState }) {
  return (
    <div>
      <Head>
        <title>Peter resume portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation _initialState={_initialState} />
      <Header />
      <Stack />
      <Work />
      <Contact />
    </div>
  );
}
